### ISSUE TITLE
cannot load such file -- metadata-json-lint/rake_task

### ISSUE THREAD

**Issue by dannygoulder** [voxpupuli/metadata-json-lint#36]
just done a bundle install (forked sgnl05/sssd and made a few changes) and i get the above error when running rake

using ruby 2.1.0 from PE 2012.2.1 agent install.

Am i doing something wrong?

If i use 0.0.11 i don't get the error and the rake task succeeds:

```
$ rake metadata_lint --trace
rake aborted!
cannot load such file -- metadata-json-lint/rake_task
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/xxx/github/sgnl05-sssd/Rakefile:6:in `<top (required)>'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load_rakefile'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:637:in `raw_load_rakefile'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:94:in `block in load_rakefile'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:93:in `load_rakefile'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:77:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/opt/puppetlabs/puppet/bin/rake:33:in `<main>'
```

Do I need to pin 0.0.11 in the Gemfile for now?

**Comment by dannygoulder** [comment]
Never mind.  I must have been doing something stupid.  The new beaker release has screwed something up in my environment I think
